"""M5-B2 complete canonical schema

Revision ID: f5c99add306d
Revises: 
Create Date: 2026-09-28 10:42:59.126411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5c99add306d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_commodity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commodity_name', sa.String(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=True),
    sa.Column('vernacular_name', sa.String(), nullable=True),
    sa.Column('food_category', sa.String(), nullable=True),
    sa.Column('origin_region', sa.String(), nullable=True),
    sa.Column('processing_state', sa.Enum('RAW', 'FRESH_CUT', 'PROCESSED', name='processingstate'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_commodity_commodity_name'), 'food_commodity', ['commodity_name'], unique=False)
    op.create_table('microbial_organism',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organism_name', sa.String(), nullable=False),
    sa.Column('organism_type', sa.String(), nullable=True),
    sa.Column('strain', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microbial_organism_organism_name'), 'microbial_organism', ['organism_name'], unique=False)
    op.create_table('packaging_material',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_name', sa.String(), nullable=False),
    sa.Column('brand_grade', sa.String(), nullable=True),
    sa.Column('structure_type', sa.Enum('MONOLAYER', 'MULTILAYER', 'COATED', name='structuretype'), nullable=True),
    sa.Column('layer_sequence', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packaging_material_material_name'), 'packaging_material', ['material_name'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=True),
    sa.Column('dataset_type', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('governance_rule', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_source_source_name'), 'source', ['source_name'], unique=False)
    op.create_table('evidence_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('record_identifier_in_source', sa.String(), nullable=True),
    sa.Column('evidence_classification', sa.Enum('EXPERIMENTAL_LITERATURE_DATA', 'MODEL_PREDICTED', 'SOURCE_MEASURED', name='evidenceclassification'), nullable=True),
    sa.Column('verification_status', sa.Enum('VERIFIED_EXTRACT', 'PARTIALLY_VERIFIED', 'PREDICTIVE_ONLY', name='verificationstatus'), nullable=True),
    sa.Column('literature_references', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('outlier_annotation', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('synthetic_prediction_warning', sa.String(), nullable=True),
    sa.Column('raw_json_payload', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_record_evidence_classification'), 'evidence_record', ['evidence_classification'], unique=False)
    op.create_index(op.f('ix_evidence_record_record_identifier_in_source'), 'evidence_record', ['record_identifier_in_source'], unique=False)
    op.create_index(op.f('ix_evidence_record_source_id'), 'evidence_record', ['source_id'], unique=False)
    op.create_index(op.f('ix_evidence_record_verification_status'), 'evidence_record', ['verification_status'], unique=False)
    op.create_table('data_transformation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('original_value', sa.String(), nullable=True),
    sa.Column('transformed_value', sa.String(), nullable=True),
    sa.Column('transformation_type', sa.String(), nullable=True),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_transformation_evidence_id'), 'data_transformation', ['evidence_id'], unique=False)
    op.create_table('food_observation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('commodity_id', sa.UUID(), nullable=False),
    sa.Column('property_name', sa.String(), nullable=False),
    sa.Column('original_value', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_min', sa.Float(), nullable=True),
    sa.Column('value_max', sa.Float(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('is_range', sa.Boolean(), nullable=True),
    sa.Column('missingness_status', sa.Enum('NOT_REPORTED', 'UNKNOWN', 'BELOW_DETECTION_LIMIT', 'NOT_APPLICABLE', name='missingnessstatus'), nullable=True),
    sa.Column('original_unit', sa.String(), nullable=True),
    sa.Column('canonical_unit', sa.String(), nullable=True),
    sa.Column('measurement_method', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['commodity_id'], ['food_commodity.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_observation_commodity_id'), 'food_observation', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_food_observation_evidence_id'), 'food_observation', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_food_observation_property_name'), 'food_observation', ['property_name'], unique=False)
    op.create_table('material_barrier_observation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('property_type', sa.Enum('OTR', 'CO2TR', 'WVTR', name='propertytype'), nullable=False),
    sa.Column('original_value', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_min', sa.Float(), nullable=True),
    sa.Column('value_max', sa.Float(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('is_range', sa.Boolean(), nullable=True),
    sa.Column('missingness_status', sa.Enum('NOT_REPORTED', 'UNKNOWN', 'BELOW_DETECTION_LIMIT', 'NOT_APPLICABLE', name='missingnessstatus'), nullable=True),
    sa.Column('original_unit', sa.String(), nullable=True),
    sa.Column('canonical_unit', sa.String(), nullable=True),
    sa.Column('test_temperature_c_value', sa.Float(), nullable=True),
    sa.Column('test_temperature_c_operator', sa.String(), nullable=True),
    sa.Column('test_rh_percent_value', sa.Float(), nullable=True),
    sa.Column('test_rh_percent_operator', sa.String(), nullable=True),
    sa.Column('thickness_value', sa.Float(), nullable=True),
    sa.Column('thickness_unit', sa.String(), nullable=True),
    sa.Column('test_method', sa.String(), nullable=True),
    sa.CheckConstraint('thickness_value >= 0 OR thickness_value IS NULL', name='ck_mbo_thickness_nonneg'),
    sa.CheckConstraint('value >= 0 OR value IS NULL', name='ck_mbo_value_nonneg'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_record.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['packaging_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_barrier_observation_evidence_id'), 'material_barrier_observation', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_material_barrier_observation_material_id'), 'material_barrier_observation', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_barrier_observation_property_type'), 'material_barrier_observation', ['property_type'], unique=False)
    op.create_table('microbial_cardinal_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('organism_id', sa.UUID(), nullable=False),
    sa.Column('temperature_min_c', sa.Float(), nullable=True),
    sa.Column('temperature_opt_c', sa.Float(), nullable=True),
    sa.Column('temperature_max_c', sa.Float(), nullable=True),
    sa.Column('water_activity_aw_min', sa.Float(), nullable=True),
    sa.Column('ph_min', sa.Float(), nullable=True),
    sa.Column('ph_opt', sa.Float(), nullable=True),
    sa.Column('ph_max', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_record.id'], ),
    sa.ForeignKeyConstraint(['organism_id'], ['microbial_organism.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microbial_cardinal_parameters_evidence_id'), 'microbial_cardinal_parameters', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_microbial_cardinal_parameters_organism_id'), 'microbial_cardinal_parameters', ['organism_id'], unique=False)
    op.create_table('microbial_gas_inhibition_response',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('organism_id', sa.UUID(), nullable=False),
    sa.Column('co2_sensitivity', sa.String(), nullable=True),
    sa.Column('minimum_co2_inhibition_percent', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.CheckConstraint('minimum_co2_inhibition_percent >= 0 AND minimum_co2_inhibition_percent <= 100 OR minimum_co2_inhibition_percent IS NULL', name='ck_mgir_co2_pct'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_record.id'], ),
    sa.ForeignKeyConstraint(['organism_id'], ['microbial_organism.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microbial_gas_inhibition_response_evidence_id'), 'microbial_gas_inhibition_response', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_microbial_gas_inhibition_response_organism_id'), 'microbial_gas_inhibition_response', ['organism_id'], unique=False)
    op.create_table('microbial_growth_kinetics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('organism_id', sa.UUID(), nullable=False),
    sa.Column('temperature_c_value', sa.Float(), nullable=True),
    sa.Column('temperature_c_operator', sa.String(), nullable=True),
    sa.Column('ph_value', sa.Float(), nullable=True),
    sa.Column('ph_operator', sa.String(), nullable=True),
    sa.Column('water_activity_aw_value', sa.Float(), nullable=True),
    sa.Column('water_activity_aw_operator', sa.String(), nullable=True),
    sa.Column('specific_growth_rate_mu_max_1_h', sa.Float(), nullable=True),
    sa.Column('lag_time_lambda_h', sa.Float(), nullable=True),
    sa.Column('atmosphere_condition', sa.String(), nullable=True),
    sa.Column('missingness_status', sa.Enum('NOT_REPORTED', 'UNKNOWN', 'BELOW_DETECTION_LIMIT', 'NOT_APPLICABLE', name='missingnessstatus'), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_record.id'], ),
    sa.ForeignKeyConstraint(['organism_id'], ['microbial_organism.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microbial_growth_kinetics_evidence_id'), 'microbial_growth_kinetics', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_microbial_growth_kinetics_organism_id'), 'microbial_growth_kinetics', ['organism_id'], unique=False)
    op.create_table('postharvest_gas_tolerances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('commodity_id', sa.UUID(), nullable=False),
    sa.Column('target_o2_min_percent', sa.Float(), nullable=True),
    sa.Column('target_o2_max_percent', sa.Float(), nullable=True),
    sa.Column('target_co2_min_percent', sa.Float(), nullable=True),
    sa.Column('target_co2_max_percent', sa.Float(), nullable=True),
    sa.Column('min_o2_fermentation_limit_percent', sa.Float(), nullable=True),
    sa.Column('max_co2_injury_limit_percent', sa.Float(), nullable=True),
    sa.CheckConstraint('target_co2_max_percent >= 0 OR target_co2_max_percent IS NULL', name='ck_pgt_co2_max_nonneg'),
    sa.CheckConstraint('target_o2_min_percent >= 0 OR target_o2_min_percent IS NULL', name='ck_pgt_o2_min_nonneg'),
    sa.ForeignKeyConstraint(['commodity_id'], ['food_commodity.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postharvest_gas_tolerances_commodity_id'), 'postharvest_gas_tolerances', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_postharvest_gas_tolerances_evidence_id'), 'postharvest_gas_tolerances', ['evidence_id'], unique=False)
    op.create_table('postharvest_storage_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('commodity_id', sa.UUID(), nullable=False),
    sa.Column('optimum_temperature_c', sa.Float(), nullable=True),
    sa.Column('optimum_rh_percent', sa.Float(), nullable=True),
    sa.Column('chilling_injury_threshold_c', sa.Float(), nullable=True),
    sa.Column('ambient_shelf_life_days', sa.Float(), nullable=True),
    sa.Column('map_shelf_life_days', sa.Float(), nullable=True),
    sa.CheckConstraint('optimum_rh_percent >= 0 AND optimum_rh_percent <= 100 OR optimum_rh_percent IS NULL', name='ck_psl_rh_pct'),
    sa.ForeignKeyConstraint(['commodity_id'], ['food_commodity.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postharvest_storage_limits_commodity_id'), 'postharvest_storage_limits', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_postharvest_storage_limits_evidence_id'), 'postharvest_storage_limits', ['evidence_id'], unique=False)
    op.create_table('respiration_observation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('commodity_id', sa.UUID(), nullable=False),
    sa.Column('gas_species', sa.Enum('O2', 'CO2', name='gasspecies'), nullable=False),
    sa.Column('temperature_c_value', sa.Float(), nullable=True),
    sa.Column('temperature_c_min', sa.Float(), nullable=True),
    sa.Column('temperature_c_max', sa.Float(), nullable=True),
    sa.Column('temperature_c_operator', sa.String(), nullable=True),
    sa.Column('original_rate_value', sa.String(), nullable=True),
    sa.Column('rate_value', sa.Float(), nullable=True),
    sa.Column('rate_min', sa.Float(), nullable=True),
    sa.Column('rate_max', sa.Float(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('is_range', sa.Boolean(), nullable=True),
    sa.Column('missingness_status', sa.Enum('NOT_REPORTED', 'UNKNOWN', 'BELOW_DETECTION_LIMIT', 'NOT_APPLICABLE', name='missingnessstatus'), nullable=True),
    sa.Column('original_unit', sa.String(), nullable=True),
    sa.Column('canonical_unit', sa.String(), nullable=True),
    sa.Column('respiratory_quotient', sa.Float(), nullable=True),
    sa.CheckConstraint('rate_value >= 0 OR rate_value IS NULL', name='ck_respiration_rate_nonneg'),
    sa.ForeignKeyConstraint(['commodity_id'], ['food_commodity.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_respiration_observation_commodity_id'), 'respiration_observation', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_respiration_observation_evidence_id'), 'respiration_observation', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_respiration_observation_gas_species'), 'respiration_observation', ['gas_species'], unique=False)
    op.create_table('validation_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('dataset', sa.String(), nullable=True),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('rule', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('original_value', sa.String(), nullable=True),
    sa.Column('normalized_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_result_evidence_id'), 'validation_result', ['evidence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_result_evidence_id'), table_name='validation_result')
    op.drop_table('validation_result')
    op.drop_index(op.f('ix_respiration_observation_gas_species'), table_name='respiration_observation')
    op.drop_index(op.f('ix_respiration_observation_evidence_id'), table_name='respiration_observation')
    op.drop_index(op.f('ix_respiration_observation_commodity_id'), table_name='respiration_observation')
    op.drop_table('respiration_observation')
    op.drop_index(op.f('ix_postharvest_storage_limits_evidence_id'), table_name='postharvest_storage_limits')
    op.drop_index(op.f('ix_postharvest_storage_limits_commodity_id'), table_name='postharvest_storage_limits')
    op.drop_table('postharvest_storage_limits')
    op.drop_index(op.f('ix_postharvest_gas_tolerances_evidence_id'), table_name='postharvest_gas_tolerances')
    op.drop_index(op.f('ix_postharvest_gas_tolerances_commodity_id'), table_name='postharvest_gas_tolerances')
    op.drop_table('postharvest_gas_tolerances')
    op.drop_index(op.f('ix_microbial_growth_kinetics_organism_id'), table_name='microbial_growth_kinetics')
    op.drop_index(op.f('ix_microbial_growth_kinetics_evidence_id'), table_name='microbial_growth_kinetics')
    op.drop_table('microbial_growth_kinetics')
    op.drop_index(op.f('ix_microbial_gas_inhibition_response_organism_id'), table_name='microbial_gas_inhibition_response')
    op.drop_index(op.f('ix_microbial_gas_inhibition_response_evidence_id'), table_name='microbial_gas_inhibition_response')
    op.drop_table('microbial_gas_inhibition_response')
    op.drop_index(op.f('ix_microbial_cardinal_parameters_organism_id'), table_name='microbial_cardinal_parameters')
    op.drop_index(op.f('ix_microbial_cardinal_parameters_evidence_id'), table_name='microbial_cardinal_parameters')
    op.drop_table('microbial_cardinal_parameters')
    op.drop_index(op.f('ix_material_barrier_observation_property_type'), table_name='material_barrier_observation')
    op.drop_index(op.f('ix_material_barrier_observation_material_id'), table_name='material_barrier_observation')
    op.drop_index(op.f('ix_material_barrier_observation_evidence_id'), table_name='material_barrier_observation')
    op.drop_table('material_barrier_observation')
    op.drop_index(op.f('ix_food_observation_property_name'), table_name='food_observation')
    op.drop_index(op.f('ix_food_observation_evidence_id'), table_name='food_observation')
    op.drop_index(op.f('ix_food_observation_commodity_id'), table_name='food_observation')
    op.drop_table('food_observation')
    op.drop_index(op.f('ix_data_transformation_evidence_id'), table_name='data_transformation')
    op.drop_table('data_transformation')
    op.drop_index(op.f('ix_evidence_record_verification_status'), table_name='evidence_record')
    op.drop_index(op.f('ix_evidence_record_source_id'), table_name='evidence_record')
    op.drop_index(op.f('ix_evidence_record_record_identifier_in_source'), table_name='evidence_record')
    op.drop_index(op.f('ix_evidence_record_evidence_classification'), table_name='evidence_record')
    op.drop_table('evidence_record')
    op.drop_index(op.f('ix_source_source_name'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_packaging_material_material_name'), table_name='packaging_material')
    op.drop_table('packaging_material')
    op.drop_index(op.f('ix_microbial_organism_organism_name'), table_name='microbial_organism')
    op.drop_table('microbial_organism')
    op.drop_index(op.f('ix_food_commodity_commodity_name'), table_name='food_commodity')
    op.drop_table('food_commodity')
    # ### end Alembic commands ###
